<?php 
    $defaultLang = ($metadataLang != '') ? $metadataLang : get_option(UPCLOO_DEFAULT_LANG);
    $languages = array(
        'it' => __('Italian', 'wp_upcloo'),
        'en' => __('English', 'wp_upcloo')
    );
?>
<label for="<?php echo UPCLOO_META_LANG?>">
    <?php _e("Select the language of your article/page", 'wp_upcloo' )?>
</label>
<select name="'.UPCLOO_META_LANG.'">
    <?php 
        foreach ($languages as $code => $language) :
    ?>
    <option value="<?php echo $code?>" <?php echo (($code == $defaultLang) ? 'selected="selected"' : '')?>><?php echo __($language, 'wp_upcloo'); ?></option>
    <?php 
        endforeach;
    ?>
</select>
