<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<?php 
foreach ($this->userSelected as $key => $postType) :
    $args = array(
        'numberposts'     => 50000,
        'offset'          => 0,
        'orderby'         => 'post_date',
        'order'           => 'DESC',
        'post_type'       => $postType,
        'post_status'     => 'publish'
    );

    $posts = get_posts( $args );   
    foreach ($posts as $post) :
        $permalink = get_permalink($post->ID);
?>
    <url><loc><?php echo $permalink ?></loc></url>
<?php 
    endforeach;
endforeach;
?>
</urlset>