<div class="upcloo-related-contents">
    <?php 
    //User override the default label
    if (!(get_option(UPCLOO_REWRITE_PUBLIC_LABEL)) || trim(get_option(UPCLOO_REWRITE_PUBLIC_LABEL)) == '') :
    ?>
    <h2><?php echo __("Maybe you are interested at", "wp_upcloo") ?>:</h2>
    <?php else: ?>
    <h2><?php echo get_option(UPCLOO_REWRITE_PUBLIC_LABEL);?></h2>
    <?php endif; ?>

    <ul>
        <?php 
        $index = 0;
        foreach ($this->listOfModels as $element) :
            if (is_int($this->maxContents) && $this->maxContents > 0) {
                if ($index >= $this->maxContents) {
                    break;
                    $index=0;
                }
        
                $index++;
            }
        ?>
        <li>
            <a href='<?php echo upcloo_get_utm_tag_url($element["url"]); ?>' <?php echo ((upcloo_is_external_site($element["url"])) ? 'target="_blank"' : '');?>>
                <?php echo $element["title"]?>
            </a>
        </li>    
        <?php endforeach; ?>
    </ul>
    
</div>