<div class='upcloo-suggest-widget'></div>
<script>
(function(g,d,id){
  upCloo = g.upCloo || []; 
  upCloo.push(
    {
        "pageId" : "<?php echo $this->permalink; ?>",
        "siteKey" : "<?php echo $this->sitekey; ?>",
        <?php echo (($this->vsitekey) ? "\"vsitekey\":\"{$this->vsitekey}\"," : ""); ?>
        "opts": {
            "sendBeacon":true,
            "headline":"<?php echo $this->headline; ?>",
            "limit":<?php echo $this->limit; ?>,
            "theme":"<?php echo $this->theme; ?>",
            "type":"<?php echo $this->type; ?>",
            "showImage": <?php echo $this->image; ?>
        }
    }
  );
  var s = d.createElement('script') , n = d.getElementsByTagName('script')[0]; 
  s.type = 'text/javascript';
  s.async = true;s.id = id;
  s.src = '//repository.upcloo.com/a/u.js';
  !d.getElementById(id) ? n.parentNode.insertBefore(s,n) :false;
})(this,document,'upcloo_js_sdk')
</script>
