<script>
(function(g,opts) {
     g.upCloo = g.upCloo || {};
     g.upCloo.bootStrap = opts;
    var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true;
        s.src = '//repository.upcloo.com/a/u.js'
    var n = document.getElementsByTagName('script')[0];
        n.parentNode.insertBefore(s,n);
})(this,{
    "pageId" : "<?php echo $this->permalink; ?>",
    "siteKey" : "<?php echo $this->sitekey; ?>",
    <?php echo (($this->vsitekey) ? "\"vsitekey\":\"{$this->vsitekey}\"" : ""); ?>
    "opts":{
        "sendBeacon":true,
        "widget":{"opts":{"headline":"<?php echo $this->headline; ?>"}}
    }
});
</script>
