<div class="upcloo-related-contents">
    <?php 
    //User override the default label
    if (!(get_option(UPCLOO_REWRITE_PUBLIC_LABEL)) || trim(get_option(UPCLOO_REWRITE_PUBLIC_LABEL)) == '') :
    ?>
    <h2><?php echo __("Maybe you are interested at", "wp_upcloo") ?>:</h2>
    <?php else: ?>
    <h2><?php echo get_option(UPCLOO_REWRITE_PUBLIC_LABEL);?></h2>
    <?php endif; ?>
    
    <?php 
        foreach ($listOfModels as $element) :
    ?>
    <div class="upcloo_template_element">';
        <?php 
        //Show if featured image
        if (get_option('upcloo_template_show_featured_image', 'wp_upcloo') == 1) :
            //Get the image path
            $imagePath =  ((is_string($element["image"])) ? $element["image"] : get_option(UPCLOO_MISSING_IMAGE_PLACEHOLDER));
            //Append the image to the content
        ?>
        <div class="upcloo_post_image">
            <a href="<?php echo upcloo_get_utm_tag_url($element["url"]);?>" <?php echo ((upcloo_is_external_site($element["url"])) ? 'target="_blank"' : '')?>>
                <img src="<?php echo $imagePath ?>" alt="" />
            </a>
        </div>
        <?php
            endif; 
        ?>
        
        <?php 
        //Show if title
        if (get_option('upcloo_template_show_title', 'wp_upcloo') == 1) :
        ?>
        <div class="upcloo_post_title">    
            <a href="<?php echo upcloo_get_utm_tag_url($element["url"]);?>" <?php echo ((upcloo_is_external_site($element["url"])) ? 'target="_blank"' : '');?>>
                <?php echo $element["title"] ?>
            </a>
        </div>';
        <?php endif;?>
        
        <?php     
            //Show if summary
            if (get_option('upcloo_template_show_summary', 'wp_upcloo') == 1) :
        ?>
        <div class="upcloo_post_summary"><?php echo $element["description"] ?></div>
        <?php 
            endif; 
        ?>

        <?php 
            //Show if categories
            if (get_option('upcloo_template_show_categories', 'wp_upcloo') == 1) :
        ?>
                
        <div class="upcloo_post_categories">
            <?php 
                foreach ($element["categories"] as $category) :
            ?>
            <div class="upcloo_post_categories_category"><?php echo $category;?></div>
            <?php endforeach; ?>
        </div>
        <?php 
            endif; 
        ?>
        
        <?php 
            //Show if tags
            if (get_option('upcloo_template_show_tags', 'wp_upcloo') == 1) :
        ?>
        <div class="upcloo_post_tags">"
            <?php 
                foreach ($element["tags"] as $tag) :
            ?>
            <div class="upcloo_post_tags_tag"><?php echo $tag ?></div>
            <?php 
                endforeach;
            ?>
        </div>
        <?php endif;?>                    
    </div>
    <?php 
        endforeach;
    ?>
</div>
